// v10
// v12
package uk.gov.hmrc.rules.build;

import uk.gov.hmrc.rules.templates.WhenTemplates;
import uk.gov.hmrc.rules.templates.ThenTemplates;

import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * DslrBuilder v12
 * - RuleRow.procCats and decTypes are now Strings (not lists)
 * - Expands decTypes == "ALL" -> A,D,Y,Z,C,J,F (for ${decTypesExpanded})
 * - Keeps raw strings available as-is for ${procCats} and ${decTypes}
 * - Stages each condition line into br.dsl if missing in main.dsl
 */
public class DslrBuilder {
    private static final List<String> ALL_DECL_TYPES = List.of("A","D","Y","Z","C","J","F");

    private final WhenTemplates whenTemplates;
    private final ThenTemplates thenTemplates;

    public DslrBuilder(WhenTemplates whenTemplates, ThenTemplates thenTemplates) {
        this.whenTemplates = Objects.requireNonNull(whenTemplates, "whenTemplates");
        this.thenTemplates = Objects.requireNonNull(thenTemplates, "thenTemplates");
    }

    public void buildDslr(List<RuleRow> rows, Path mainDsl, Path brDsl, Path outDslr) {
        if (rows == null || rows.isEmpty()) throw new IllegalArgumentException("rows must not be null/empty");
        Objects.requireNonNull(mainDsl, "mainDsl");
        Objects.requireNonNull(brDsl, "brDsl");
        Objects.requireNonNull(outDslr, "outDslr");

        var ordered = new ArrayList<>(rows);
        ordered.sort(Comparator.comparing(RuleRow::ruleName, Comparator.nullsLast(String::compareTo)));

        var dslr = new StringBuilder();
        writeHeader(dslr, ordered.size());

        var stagedCache = FileIO.fileReadAllLines(brDsl);

        for (RuleRow r : ordered) {
            validateRow(r);

            // 1) Stage each condition into br.dsl if missing in main.dsl
            for (var c : r.conditions()) {
                var line = normalizeCondition(c);
                ensureLhsExistsOrStage(line, mainDsl, brDsl, stagedCache);
            }

            // 2) Prepare bindings
            var effBindings = effectiveBindings(r);

            // 3) Render WHEN/THEN via templates
            var when = whenTemplates.render(nonNull(r.whenTemplateId()), effBindings);
            var then = thenTemplates.render(nonNull(r.thenTemplateId()), effBindings);

            // 4) Emit rule (include original source as comment)
            if (!isBlank(r.original())) {
                dslr.append("// source: ").append(r.original().replace("\n", " ")).append("\n");
            }
            dslr.append("""
                rule "%s"
                when
                %s
                then
                %s
                end

                """.formatted(r.ruleName(), when, then));
        }

        FileIO.writeString(outDslr, dslr.toString());
    }

    private Map<String, Object> effectiveBindings(RuleRow r) {
        var map = new LinkedHashMap<>(Optional.ofNullable(r.bindings()).orElseGet(LinkedHashMap::new));

        // Always provide raw strings
        map.putIfAbsent("procCats", nonNull(r.procCats()).trim());
        map.putIfAbsent("decTypes", nonNull(r.decTypes()).trim());

        // Provide expanded dec types as a comma-joined string (for convenience)
        var decExpanded = expandDecTypesToString(r.decTypes());
        map.putIfAbsent("decTypesExpanded", decExpanded);

        // Auto-inject error code if not present
        if (!map.containsKey("code") && !isBlank(r.errorCode())) {
            map.put("code", r.errorCode());
        }

        // ${conditions} (newline-joined + indent for WHEN body)
        var joinedConds = String.join("\n        ", r.conditions());
        map.putIfAbsent("conditions", joinedConds);

        return map;
    }

    private String expandDecTypesToString(String raw) {
        if (raw == null) return "";
        if ("ALL".equalsIgnoreCase(raw.trim())) {
            return String.join(",", ALL_DECL_TYPES);
        }
        // normalize commas and spaces
        var parts = Arrays.stream(raw.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .toList();
        return String.join(",", parts);
    }

    private String normalizeCondition(String c) {
        return c == null ? "" : c.trim().replaceAll("\\s+", " ");
    }

    private void writeHeader(StringBuilder sb, int count) {
        var ts = ZonedDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        sb.append("""
            // --------------------------------------------------------------------
            // Generated by DslrBuilder v12 at %s
            // Rules: %d
            // --------------------------------------------------------------------

            """.formatted(ts, count));
    }

    private void validateRow(RuleRow r) {
        if (r == null) throw new IllegalArgumentException("RuleRow is null");
        if (isBlank(r.ruleName())) throw new IllegalArgumentException("ruleName is blank");
        if (r.conditions() == null || r.conditions().isEmpty()) {
            throw new IllegalArgumentException("conditions list is null/empty for rule: " + r.ruleName());
        }
        if (isBlank(r.whenTemplateId())) throw new IllegalArgumentException("whenTemplateId is blank");
        if (isBlank(r.thenTemplateId())) throw new IllegalArgumentException("thenTemplateId is blank");
    }

    private boolean isBlank(String s) { return s == null || s.trim().isEmpty(); }
    private String nonNull(String s) { return s == null ? "" : s; }

    private void ensureLhsExistsOrStage(String lhsLine, Path mainDsl, Path brDsl, Set<String> stagedCache) {
        var normalized = lhsLine.trim();
        if (normalized.isEmpty()) return;
        if (FileIO.fileContainsLine(mainDsl, normalized)) return;
        if (!stagedCache.contains(normalized)) {
            FileIO.appendLine(brDsl, normalized);
            stagedCache.add(normalized);
        }
    }
}