// v8
package uk.gov.hmrc.rules;

import uk.gov.hmrc.rules.templates.WhenTemplates;
import uk.gov.hmrc.rules.templates.ThenTemplates;

import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * DslrBuilder v8
 * - Keeps original 2 params: WhenTemplates + ThenTemplates
 * - Idempotent LHS staging: only appends to br.dsl if missing in main.dsl AND not already staged
 * - Deterministic rule ordering (by ruleName) to avoid noisy diffs
 * - Defensive null/empty checks with clear messages
 * - Single pass file writes (string builder -> write once)
 */
public class DslrBuilder {
    private final WhenTemplates whenTemplates; // param 1
    private final ThenTemplates thenTemplates; // param 2

    public DslrBuilder(WhenTemplates whenTemplates, ThenTemplates thenTemplates) {
        this.whenTemplates = Objects.requireNonNull(whenTemplates, "whenTemplates");
        this.thenTemplates = Objects.requireNonNull(thenTemplates, "thenTemplates");
    }

    /**
     * Build DSLR output and stage missing LHS entries.
     *
     * @param rows    parsed rows for rules
     * @param mainDsl path to main.dsl (checked for existing LHS handles)
     * @param brDsl   path to br.dsl (staging for missing LHS handles)
     * @param outDslr path to generated .dslr file
     */
    public void buildDslr(List<RuleRow> rows, Path mainDsl, Path brDsl, Path outDslr) {
        if (rows == null || rows.isEmpty()) {
            throw new IllegalArgumentException("rows must not be null/empty");
        }
        Objects.requireNonNull(mainDsl, "mainDsl");
        Objects.requireNonNull(brDsl, "brDsl");
        Objects.requireNonNull(outDslr, "outDslr");

        // Sort to keep output stable between runs
        var ordered = new ArrayList<>(rows);
        ordered.sort(Comparator.comparing(RuleRow::ruleName, Comparator.nullsLast(String::compareTo)));

        var dslr = new StringBuilder();
        writeHeader(dslr, ordered.size());

        // Preload existing staged lines to keep idempotent behavior
        var stagedCache = FileIO.fileReadAllLines(brDsl);

        for (RuleRow r : ordered) {
            validateRow(r);

            // Ensure LHS exists in main.dsl; if not, stage to br.dsl (idempotently)
            ensureLhsExistsOrStage(r.lhsKey(), mainDsl, brDsl, stagedCache);

            // Render WHEN/THEN from templates with bindings
            var when = whenTemplates.render(r.whenTemplateId(), r.bindings());
            var then = thenTemplates.render(r.thenTemplateId(), r.bindings());

            // Emit rule block
            dslr.append("""
                rule "%s"
                when
                %s
                then
                %s
                end

                """.formatted(r.ruleName(), when, then));
        }

        FileIO.writeString(outDslr, dslr.toString());
    }

    private void writeHeader(StringBuilder sb, int count) {
        var ts = ZonedDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        sb.append("""
            // --------------------------------------------------------------------
            // Generated by DslrBuilder v8 at %s
            // Rules: %d
            // --------------------------------------------------------------------

            """.formatted(ts, count));
    }

    private void validateRow(RuleRow r) {
        if (r == null) throw new IllegalArgumentException("RuleRow is null");
        if (isBlank(r.ruleName())) throw new IllegalArgumentException("ruleName is blank");
        if (isBlank(r.lhsKey())) throw new IllegalArgumentException("lhsKey is blank");
        if (isBlank(r.whenTemplateId())) throw new IllegalArgumentException("whenTemplateId is blank");
        if (isBlank(r.thenTemplateId())) throw new IllegalArgumentException("thenTemplateId is blank");
        if (r.bindings() == null) throw new IllegalArgumentException("bindings is null");
    }

    private boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }

    /** Idempotent: checks main.dsl; if missing there and not already in br.dsl, appends once. */
    private void ensureLhsExistsOrStage(String lhsKey, Path mainDsl, Path brDsl, Set<String> stagedCache) {
        var normalized = lhsKey.trim();
        if (normalized.isEmpty()) return;

        var existsInMain = FileIO.fileContainsLine(mainDsl, normalized);
        if (existsInMain) return;

        // Only append if not already staged in br.dsl (use exact trimmed match)
        if (!stagedCache.contains(normalized)) {
            FileIO.appendLine(brDsl, normalized);
            stagedCache.add(normalized);
        }
    }
}